version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: mkdir test-results && pip install tox
      - run:
          name: Run Test Suite
          command: tox
      - store_artifacts:
          path: test-results/magpylib/
      - store_test_results:
          path: test-results/magpylib/
      - run: 
          name: See if tests are where they should be
          command: ls test-results